import { ApolloError, gql } from "@apollo/client";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { apolloClient } from "../lib/apollo";
import { CategoryType, PostType } from "../lib/typings";

const ALL_POST_QUERY = gql`
  {
    posts {
      data {
        id
        attributes {
          title
          publishedAt
          slug
          author {
            data {
              attributes {
                name
                avatar {
                  data {
                    attributes {
                      url
                    }
                  }
                }
              }
            }
          }
          cover {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
    categories {
      data {
        attributes {
          name
          slug
          cover {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
  }
`;

interface Props {
  posts: PostType[];
  categories: CategoryType[];
  error: ApolloError;
}

const Home: NextPage<Props> = ({ posts, categories, error }) => {
  if (error) return <div>{error.message}</div>;

  return (
    <div className="bg-slate-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js/Strapi Blog Starter</h1>

      <div>
        {categories.map(({ id, attributes: { name } }) => (
          <div key={id}>{name}</div>
        ))}
      </div>

      <div>
        {posts.map(({ id, attributes: { title } }) => (
          <div key={id}>{title}</div>
        ))}
      </div>

      <Link href={`/posts/${posts[0].attributes.slug}`}>
        <a>CLICK: {posts[0].attributes.title}</a>
      </Link>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { data, error } = await apolloClient.query({ query: ALL_POST_QUERY });

  if (error)
    return {
      props: { error },
    };

  return {
    props: { posts: data.posts.data, categories: data.categories.data },
    revalidate: 30,
  };

  // return {
  //   props: { posts: [] },
  // };
};

export default Home;
