import { ApolloError, gql } from "@apollo/client";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { apolloClient } from "../lib/apollo";
import styles from "../styles/Home.module.css";

const ALL_POST_QUERY = gql`
  {
    posts {
      data {
        id
        attributes {
          title
          publishedAt
          author {
            data {
              attributes {
                name
                avatar {
                  data {
                    attributes {
                      url
                    }
                  }
                }
              }
            }
          }
          cover {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
    categories {
      data {
        attributes {
          name
          cover {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
  }
`;

interface Props {
  posts: any[];
  categories: any[];
  error: ApolloError;
}

const Home: NextPage<Props> = ({ posts, categories, error }) => {
  if (error) return <div>{error.message}</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js/Strapi Blog Starter</h1>

      <div>{JSON.stringify(categories)}</div>

      <div>
        {posts.map(({ id, attributes }) => (
          <div key={id}>{attributes.title}</div>
        ))}
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { data, error } = await apolloClient.query({ query: ALL_POST_QUERY });

  if (error)
    return {
      props: { error },
    };

  return {
    props: { posts: data.posts.data, categories: data.categories.data },
    revalidate: 30,
  };

  // return {
  //   props: { posts: [] },
  // };
};

export default Home;
